function [Pk,J0,vxk]=solver1D(Jk,Dk,M)
    Pk=ones(M,1);
    Pk([1:floor(M/2) ceil(M/2)+1:end])=...
	(Jk([1:floor(M/2) ceil(M/2)+1:end],...
	[1:floor(M/2) ceil(M/2)+1:end])...
        +Dk([1:floor(M/2) ceil(M/2)+1:end],...
	[1:floor(M/2) ceil(M/2)+1:end]))\...
        -Jk([1:floor(M/2) ceil(M/2)+1:end],ceil(M/2));       
    J0=-1i*2*pi*(Jk+Dk)*Pk;
    J0=J0.'; Pk=Pk.'; 
    vxk=real(J0(ceil(M/2)));
end
